// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_bepaid is a generated GoMock package.
package mocks

import (
	responses "bepaid/responses"
	vo "bepaid/vo"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Authorizations mocks base method.
func (m *MockClientInterface) Authorizations(ctx context.Context, authorizationRequest vo.AuthorizationRequest) (*responses.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorizations", ctx, authorizationRequest)
	ret0, _ := ret[0].(*responses.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorizations indicates an expected call of Authorizations.
func (mr *MockClientInterfaceMockRecorder) Authorizations(ctx, authorizationRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorizations", reflect.TypeOf((*MockClientInterface)(nil).Authorizations), ctx, authorizationRequest)
}

// Capture mocks base method.
func (m *MockClientInterface) Capture(ctx context.Context, captureRequest vo.CaptureRequest) (*responses.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, captureRequest)
	ret0, _ := ret[0].(*responses.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockClientInterfaceMockRecorder) Capture(ctx, captureRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockClientInterface)(nil).Capture), ctx, captureRequest)
}
